create database BDFinal
go

use BDFinal
go
/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 28-nov.-2022 21:34:36 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Actividades_Voluntariado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Actividades] DROP CONSTRAINT [FK_Actividades_Voluntariado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Usuario_Persona]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Usuario] DROP CONSTRAINT [FK_Usuario_Persona]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Voluntario_Persona]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Voluntario] DROP CONSTRAINT [FK_Voluntario_Persona]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Voluntario_Voluntariado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Voluntario] DROP CONSTRAINT [FK_Voluntario_Voluntariado]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Actividades]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Actividades]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Persona]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Persona]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Voluntariado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Voluntariado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Voluntario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Voluntario]
GO

/* Create Tables */

CREATE TABLE [Actividades]
(
	[ActividadesID] nvarchar NOT NULL,
	[VoluntariadoID] int NOT NULL,
	[Fecha] nvarchar(20) NULL,
	[Hora] nvarchar(20) NULL,
	[Descripcion] nvarchar(40) NULL,
	[Estado] bit NULL
)
GO

CREATE TABLE [Persona]
(
	[PersonaID] int NOT NULL,
	[Nombres] nvarchar(50) NULL,
	[Apellidos] nvarchar(50) NULL,
	[Cedula] nvarchar(20) NULL,
	[Fechanac] nvarchar(20) NULL,
	[Celular] nvarchar(10) NULL,
	[Email] nvarchar(35) NULL
)
GO

CREATE TABLE [Usuario]
(
	[UsuarioID] int NOT NULL,
	[Password] nvarchar(50) NULL
)
GO

CREATE TABLE [Voluntariado]
(
	[VoluntariadoID] int NOT NULL IDENTITY (1, 1),
	[Nombre] nvarchar(50) NULL,
	[Tipo] nvarchar(50) NULL
)
GO

CREATE TABLE [Voluntario]
(
	[VoluntariadoID] int NOT NULL,
	[VoluntarioID] int NOT NULL IDENTITY (1, 1)
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Actividades] 
 ADD CONSTRAINT [PK_Actividades]
	PRIMARY KEY CLUSTERED ([ActividadesID] ASC)
GO

ALTER TABLE [Persona] 
 ADD CONSTRAINT [PK_Persona]
	PRIMARY KEY CLUSTERED ([PersonaID] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([UsuarioID] ASC)
GO

ALTER TABLE [Voluntariado] 
 ADD CONSTRAINT [PK_Voluntariado]
	PRIMARY KEY CLUSTERED ([VoluntariadoID] ASC)
GO

ALTER TABLE [Voluntario] 
 ADD CONSTRAINT [PK_Voluntario]
	PRIMARY KEY CLUSTERED ([VoluntarioID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Actividades] ADD CONSTRAINT [FK_Actividades_Voluntariado]
	FOREIGN KEY ([VoluntariadoID]) REFERENCES [Voluntariado] ([VoluntariadoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Usuario] ADD CONSTRAINT [FK_Usuario_Persona]
	FOREIGN KEY ([UsuarioID]) REFERENCES [Persona] ([PersonaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Voluntario] ADD CONSTRAINT [FK_Voluntario_Persona]
	FOREIGN KEY ([VoluntarioID]) REFERENCES [Persona] ([PersonaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Voluntario] ADD CONSTRAINT [FK_Voluntario_Voluntariado]
	FOREIGN KEY ([VoluntariadoID]) REFERENCES [Voluntariado] ([VoluntariadoID]) ON DELETE No Action ON UPDATE No Action
GO
